### ISSUE TITLE
Uncaught ReferenceError: userInput is not defined

### ISSUE THREAD

**Issue by jesussteve** [Hugeaclease/Hugeaclease.github.io#3]
If the user does not select either rock / paper / scissors then the following error occurs:

![image](https://user-images.githubusercontent.com/19396027/67239975-615fc600-f448-11e9-880f-13c1a3da9e36.png)

**Comment by Hugeaclease** [comment]
Nice one for finding this pal. I'll set up an if else for it with an alert on it.

**Comment by Hugeaclease** [comment]
Nipped it with an if else. Thanks again for finding it pal.
